export default {
  lang: {
    en: 'English',
    pt: 'Portuguese',
  },
  common: {
    readMore: 'Read more',
    scroll: 'SCROLL',
    toggleTheme: 'Toggle theme',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    download: 'Download',
    share: 'Share',
    copy: 'Copy',
    copied: 'Copied!',
    backToTop: 'Back to Top',
    showMore: 'Show More',
    showLess: 'Show Less',
    filter: 'Filter',
    sort: 'Sort',
    search: 'Search',
    noResults: 'No results found',
    tryAgain: 'Try Again',
    refresh: 'Refresh',
    retry: 'Retry',
    imageLoadError: 'Failed to load image',
  },
  navigation: {
    presentation: 'Home',
    about: 'About',
    companies: 'Experience',
    certifications: 'Certifications',
    skills: 'Skills',
    projects: 'Projects',
    contact: 'Contact',
    toggleMenu: 'Toggle navigation menu',
    openMenu: 'Open navigation menu',
    closeMenu: 'Close navigation menu',
    mobileMenu: 'Mobile navigation menu',
    mobileMenuOpened: 'Mobile menu opened',
    mobileMenuClosed: 'Mobile menu closed',
    scrolledToTop: 'Scrolled to top of page',
    navigatedTo: 'Navigated to {section} section',
    scrollProgress: 'Scroll Progress',
    currentSection: 'Current Section',
    goToSection: 'Go to {section}',
  },
  theme: {
    light: 'Light Mode',
    dark: 'Dark Mode',
    toggle: 'Toggle Theme',
    switching: 'Switching theme...',
    applied: 'Theme applied successfully',
    error: 'Failed to apply theme',
  },
  language: {
    current: 'Current Language',
    switch: 'Switch Language',
    switching: 'Switching language...',
    applied: 'Language changed successfully',
    error: 'Failed to change language',
    browserDefault: 'Browser Default',
  },
  home: {
    presentationSection: {
      greeting: "Hello, I'm",
      name: 'João Pedro Ennes',
      title: 'Full Stack Developer',
      summary:
        'Passionate about creating amazing digital experiences with modern technologies and clean code.',
      cta: {
        viewWork: 'View My Work',
        getInTouch: 'Get In Touch',
        downloadCV: 'Download CV',
        scrollDown: 'Scroll Down',
      },
      animation: {
        typing: 'Typing animation',
        fadeIn: 'Fade in animation',
        slideUp: 'Slide up animation',
      },
    },
    portfolioData: {
      companies: {
        nubank: {
          position: 'Software Engineer',
          description:
            'Leading development of enterprise web applications using modern technologies.',
          achievements: {
            performance: 'Improved application performance by 40%',
            leadership: 'Led a team of 5 developers',
            cicd: 'Implemented CI/CD pipeline reducing deployment time by 60%',
          },
        },
        onfly: {
          position: 'Full Stack Developer PL. II',
          description:
            'Developed custom web solutions for various clients across different industries.',
          achievements: {
            projects: 'Delivered 15+ successful projects',
            onboarding: 'Reduced client onboarding time by 50%',
            mentoring: 'Mentored junior developers',
          },
        },
        nelogica: {
          position: 'Software Developer',
          description: 'Built responsive web applications and mobile-first interfaces.',
          achievements: {
            engagement: 'Increased user engagement by 35%',
            designSystem: 'Implemented responsive design system',
            performance: 'Optimized loading times by 45%',
          },
        },
      },
      certifications: {
        awsSaa: {
          name: 'AWS Certified Solutions Architect',
          issuer: 'Amazon Web Services',
        },
        vueCertified: {
          name: 'Vue.js Certified Developer',
          issuer: 'Vue.js Foundation',
        },
        psm: {
          name: 'Professional Scrum Master I',
          issuer: 'Scrum.org',
        },
        gcpDev: {
          name: 'Google Cloud Professional Developer',
          issuer: 'Google Cloud',
        },
        mongoDev: {
          name: 'MongoDB Certified Developer',
          issuer: 'MongoDB University',
        },
      },
      projects: {
        ecommerce: {
          title: 'E-Commerce Platform',
          description:
            'A modern e-commerce platform built with Vue.js and Node.js, featuring real-time inventory management, payment processing, and admin dashboard.',
          role: 'Full Stack Developer',
          challenges: {
            inventory: 'Implementing real-time inventory synchronization',
            queries: 'Optimizing database queries for large product catalogs',
            compliance: 'Ensuring PCI compliance for payment processing',
          },
          outcomes: {
            conversion: 'Increased conversion rate by 25%',
            performance: 'Reduced page load time by 40%',
            transactions: 'Successfully processed $100K+ in transactions',
          },
        },
        taskApi: {
          title: 'Task Management API',
          description:
            'RESTful API for task management with team collaboration features, built with Node.js and MongoDB.',
          role: 'Backend Developer',
          challenges: {
            schema: 'Designing scalable database schema',
            notifications: 'Implementing real-time notifications',
            consistency: 'Ensuring data consistency across team operations',
          },
          outcomes: {
            users: 'Supports 1000+ concurrent users',
            uptime: 'Achieved 99.9% uptime',
            efficiency: 'Reduced task completion time by 30%',
          },
        },
        portfolio: {
          title: 'Portfolio Website',
          description:
            'Personal portfolio website showcasing projects and skills, built with Vue.js and modern web technologies.',
          role: 'Frontend Developer & Designer',
          challenges: {
            animations: 'Creating smooth animations and transitions',
            responsive: 'Implementing responsive design across all devices',
            optimization: 'Optimizing performance and accessibility',
          },
          outcomes: {
            lighthouse: 'Achieved 95+ Lighthouse score',
            inquiries: 'Increased client inquiries by 50%',
            featured: 'Featured in design showcases',
          },
        },
        weather: {
          title: 'Weather Dashboard',
          description:
            'Real-time weather dashboard with location-based forecasts and interactive maps.',
          role: 'Frontend Developer',
          challenges: {
            apis: 'Integrating multiple weather APIs',
            visualizations: 'Creating responsive data visualizations',
            geolocation: 'Handling geolocation and permissions',
          },
          outcomes: {
            users: 'Serves 10K+ daily active users',
            accuracy: 'Accurate forecasts with 95% reliability',
            feedback: 'Positive user feedback (4.8/5 rating)',
          },
        },
        microservices: {
          title: 'Microservices Architecture',
          description:
            'Scalable microservices architecture for a fintech application with Docker and Kubernetes.',
          role: 'DevOps Engineer',
          challenges: {
            communication: 'Designing service communication patterns',
            monitoring: 'Implementing distributed logging and monitoring',
            consistency: 'Ensuring data consistency across services',
          },
          outcomes: {
            deployment: 'Reduced deployment time by 70%',
            reliability: 'Improved system reliability to 99.95%',
            scaling: 'Enabled horizontal scaling for peak loads',
          },
        },
      },
    },
    companiesSection: {
      title: 'Professional Experience',
      subtitle: "Companies I've worked with",
      displayMode: {
        timeline: 'Timeline View',
        grid: 'Grid View',
        list: 'List View',
      },
      company: {
        position: 'Position',
        period: 'Period',
        achievements: 'Key Achievements',
        technologies: 'Technologies Used',
        current: 'Present',
        duration: 'Duration',
        location: 'Location',
        type: 'Employment Type',
        fullTime: 'Full-time',
        partTime: 'Part-time',
        contract: 'Contract',
        freelance: 'Freelance',
        internship: 'Internship',
      },
      sorting: {
        chronological: 'Chronological',
        relevance: 'By Relevance',
        company: 'By Company',
        position: 'By Position',
      },
      filters: {
        all: 'All Companies',
        byType: 'By Employment Type',
        byTechnology: 'By Technology',
        byPeriod: 'By Period',
      },
    },
    certificationsSection: {
      title: 'Certifications & Credentials',
      subtitle: 'Professional certifications and achievements',
      filters: {
        all: 'All Categories',
        category: 'Filter by Category',
        status: 'Filter by Status',
        issuer: 'Filter by Issuer',
        recent: 'Recent Only',
      },
      certification: {
        issuer: 'Issued by',
        date: 'Date',
        credentialId: 'Credential ID',
        verify: 'Verify Credential',
        expired: 'Expired',
        valid: 'Valid',
        expiresOn: 'Expires on',
        noExpiration: 'No Expiration',
        renewed: 'Renewed',
        inProgress: 'In Progress',
      },
      categories: {
        cloud: 'Cloud Computing',
        development: 'Software Development',
        security: 'Security',
        data: 'Data & Analytics',
        project: 'Project Management',
        design: 'Design',
        other: 'Other',
      },
      sorting: {
        date: 'By Date',
        name: 'By Name',
        issuer: 'By Issuer',
        category: 'By Category',
        status: 'By Status',
      },
      empty: {
        title: 'No certifications found',
        description: 'No certifications match the selected filters.',
        resetFilters: 'Reset Filters',
      },
    },
    hardSkillsSection: {
      title: 'Technical Skills',
      subtitle: 'Technologies and tools I work with',
      allCategories: 'All Categories',
      proficiency: 'Proficiency',
      years: 'Years',
      projects: 'Projects',
      experience: 'Experience Level',
      noSkills: 'No skills found for the selected category.',
      displayModes: {
        grid: 'Grid View',
        list: 'List View',
        chart: 'Chart View',
        compact: 'Compact View',
      },
      proficiencyLevels: {
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        advanced: 'Advanced',
        expert: 'Expert',
        master: 'Master',
      },
      skills: {
        frontend: {
          title: 'Frontend',
          description: 'Development of user interfaces with modern technologies.',
        },
        backend: {
          title: 'Backend',
          description: 'Development of APIs and web services with modern technologies.',
        },
        devops: {
          title: 'DevOps & Cloud',
          description: 'Configuration and management of cloud services and deployment pipelines.',
        },
        database: {
          title: 'Database',
          description: 'Database design, optimization, and management.',
        },
        mobile: {
          title: 'Mobile',
          description: 'Mobile application development for iOS and Android.',
        },
        tools: {
          title: 'Tools & Utilities',
          description: 'Development tools, IDEs, and productivity software.',
        },
      },
      filters: {
        category: 'Filter by Category',
        proficiency: 'Filter by Proficiency',
        experience: 'Filter by Experience',
        recent: 'Recently Used',
      },
    },
    projectsSection: {
      title: 'Featured Projects',
      subtitle: 'A showcase of my recent work',
      allCategories: 'All Categories',
      featuredOnly: 'Featured Only',
      featured: 'Featured',
      technologies: 'Technologies',
      challenges: 'Challenges',
      outcomes: 'Outcomes',
      viewLive: 'View Live',
      viewCode: 'View Code',
      viewDetails: 'View Details',
      noProjects: 'No projects found for the selected filters.',
      project: {
        role: 'My Role',
        duration: 'Duration',
        team: 'Team Size',
        status: 'Status',
        completed: 'Completed',
        inProgress: 'In Progress',
        planned: 'Planned',
        archived: 'Archived',
        client: 'Client',
        year: 'Year',
        category: 'Category',
      },
      categories: {
        web: 'Web Development',
        mobile: 'Mobile Apps',
        desktop: 'Desktop Applications',
        api: 'APIs & Backend',
        ecommerce: 'E-commerce',
        portfolio: 'Portfolio Sites',
        dashboard: 'Dashboards',
        game: 'Games',
        tool: 'Tools & Utilities',
        other: 'Other',
      },
      filters: {
        category: 'Filter by Category',
        technology: 'Filter by Technology',
        status: 'Filter by Status',
        year: 'Filter by Year',
        featured: 'Featured Projects Only',
      },
      sorting: {
        recent: 'Most Recent',
        featured: 'Featured First',
        name: 'By Name',
        category: 'By Category',
        technology: 'By Technology',
      },
    },
    contactSection: {
      title: 'Hire Me For Your Next Amazing Project',
      subtitle: "Let's create something extraordinary together",
      description:
        "Let's make something new, different and more meaningful or make thing more visual or conceptual? Just say hello!",
      socialInfos: {
        location: 'Belo Horizonte, MG, Brazil',
        timezone: 'UTC-3 (Brasília Time)',
        languages: 'Portuguese, English',
      },
      contactMethods: {
        title: 'Get In Touch',
        email: 'Email',
        phone: 'Phone',
        whatsapp: 'WhatsApp',
        telegram: 'Telegram',
        linkedin: 'LinkedIn',
        schedule: 'Schedule a Call',
      },
      socialLinks: {
        title: 'Follow Me',
        github: 'GitHub',
        linkedin: 'LinkedIn',
        twitter: 'Twitter',
        instagram: 'Instagram',
        youtube: 'YouTube',
        medium: 'Medium',
        dev: 'Dev.to',
      },
      availability: {
        title: 'Availability Status',
        available: 'Available for new projects',
        busy: 'Currently busy',
        unavailable: 'Not available',
        partTime: 'Available part-time',
        fullTime: 'Available full-time',
        freelance: 'Available for freelance',
        consulting: 'Available for consulting',
      },
      form: {
        title: 'Send me a message',
        subtitle: "I'll get back to you as soon as possible",
      },
      fields: {
        name: 'Your name',
        email: 'Your email address',
        company: 'Company (Optional)',
        budget: 'Your budget (Optional)',
        timeline: 'Project timeline (Optional)',
        description: 'Your project description',
        message: 'Your message',
        send: 'Send Message',
        sending: 'Sending...',
        sent: 'Message Sent!',
        reset: 'Reset Form',
      },
      budgetRanges: {
        small: 'Under $5,000',
        medium: '$5,000 - $15,000',
        large: '$15,000 - $50,000',
        enterprise: '$50,000+',
        discuss: "Let's discuss",
      },
      validation: {
        nameRequired: 'Name is required',
        nameMinLength: 'Name must be at least 2 characters',
        nameMaxLength: 'Name must be less than 50 characters',
        emailRequired: 'Email is required',
        emailInvalid: 'Please enter a valid email address',
        messageRequired: 'Message is required',
        messageMinLength: 'Message must be at least 10 characters',
        messageMaxLength: 'Message must be less than 1000 characters',
        companyMaxLength: 'Company name must be less than 100 characters',
      },
      messages: {
        success: 'Thank you! Your message has been sent successfully.',
        error: 'Sorry, there was an error sending your message. Please try again.',
        networkError: 'Network error. Please check your connection and try again.',
        serverError: 'Server error. Please try again later.',
        rateLimited: 'Too many requests. Please wait a moment before sending another message.',
      },
      notifications: {
        successTitle: 'Message Sent!',
        successMessage: "Thank you for reaching out. I'll get back to you soon.",
        errorTitle: 'Error',
        errorMessage: 'Failed to send message. Please try again later.',
        copySuccess: 'Email copied to clipboard!',
        copyError: 'Failed to copy email address.',
      },
    },
  },
  footer: {
    contact: {
      title: 'Contact Information',
    },
    social: {
      title: 'Follow Me',
      visitProfile: 'Visit my profile on',
    },
    navigation: {
      title: 'Quick Navigation',
    },
    availability: {
      title: 'Availability Status',
      status: {
        available: 'Available for new projects',
        busy: 'Currently busy',
        unavailable: 'Not available',
      },
    },
    backToTop: 'Back to Top',
    copyright: '© {year} {name}. All rights reserved.',
    madeWith: 'Made with ❤️ using Vue.js',
    version: 'Version {version}',
    lastUpdated: 'Last updated: {date}',
    links: {
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      sitemap: 'Sitemap',
      rss: 'RSS Feed',
    },
  },
  errors: {
    pageNotFound: 'Page Not Found',
    serverError: 'Server Error',
    networkError: 'Network Error',
    loadingError: 'Loading Error',
    tryAgain: 'Try Again',
    goHome: 'Go Home',
    contactSupport: 'Contact Support',
    errorCode: 'Error Code: {code}',
    errorMessage: 'Error Message: {message}',
  },
  accessibility: {
    skipToContent: 'Skip to main content',
    skipToNavigation: 'Skip to navigation',
    openInNewTab: 'Opens in new tab',
    externalLink: 'External link',
    downloadFile: 'Download file',
    toggleNavigation: 'Toggle navigation menu',
    closeModal: 'Close modal',
    previousSlide: 'Previous slide',
    nextSlide: 'Next slide',
    playVideo: 'Play video',
    pauseVideo: 'Pause video',
    muteVideo: 'Mute video',
    unmuteVideo: 'Unmute video',
    fullscreen: 'Enter fullscreen',
    exitFullscreen: 'Exit fullscreen',
    loading: 'Content is loading',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    filterResults: 'Filter results',
    clearFilters: 'Clear all filters',
    searchResults: '{count} results found',
    noSearchResults: 'No search results found',
    pageOf: 'Page {current} of {total}',
    itemsPerPage: 'Items per page',
  },
}
