export default {
  lang: {
    en: 'Inglês',
    pt: 'Português',
  },
  common: {
    readMore: 'Saiba mais',
    scroll: 'SCROLL',
    toggleTheme: 'Alternar tema',
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    warning: 'Aviso',
    info: 'Informação',
    close: 'Fechar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Salvar',
    edit: 'Editar',
    delete: 'Excluir',
    view: 'Visualizar',
    download: 'Baixar',
    share: 'Compartilhar',
    copy: 'Copiar',
    copied: 'Copiado!',
    backToTop: 'Voltar ao Topo',
    showMore: 'Mostrar Mais',
    showLess: 'Mostrar Menos',
    filter: 'Filtrar',
    sort: 'Ordenar',
    search: 'Pesquisar',
    noResults: 'Nenhum resultado encontrado',
    tryAgain: 'Tentar Novamente',
    refresh: 'Atualizar',
    retry: 'Tentar Novamente',
    imageLoadError: 'Falha ao carregar imagem',
  },
  navigation: {
    presentation: 'Início',
    about: 'Sobre',
    companies: 'Experiência',
    certifications: 'Certificações',
    skills: 'Habilidades',
    projects: 'Projetos',
    contact: 'Contato',
    toggleMenu: 'Alternar menu de navegação',
    openMenu: 'Abrir menu de navegação',
    closeMenu: 'Fechar menu de navegação',
    mobileMenu: 'Menu de navegação móvel',
    mobileMenuOpened: 'Menu móvel aberto',
    mobileMenuClosed: 'Menu móvel fechado',
    scrolledToTop: 'Rolado para o topo da página',
    navigatedTo: 'Navegado para a seção {section}',
    scrollProgress: 'Progresso da Rolagem',
    currentSection: 'Seção Atual',
    goToSection: 'Ir para {section}',
  },
  theme: {
    light: 'Modo Claro',
    dark: 'Modo Escuro',
    toggle: 'Alternar Tema',
    switching: 'Alterando tema...',
    applied: 'Tema aplicado com sucesso',
    error: 'Falha ao aplicar tema',
  },
  language: {
    current: 'Idioma Atual',
    switch: 'Alterar Idioma',
    switching: 'Alterando idioma...',
    applied: 'Idioma alterado com sucesso',
    error: 'Falha ao alterar idioma',
    browserDefault: 'Padrão do Navegador',
  },
  home: {
    presentationSection: {
      greeting: 'Olá, eu sou',
      name: 'João Pedro Ennes',
      title: 'Desenvolvedor Full Stack',
      summary:
        'Apaixonado por criar experiências digitais incríveis com tecnologias modernas e código limpo.',
      cta: {
        viewWork: 'Ver Meu Trabalho',
        getInTouch: 'Entre em Contato',
        downloadCV: 'Baixar CV',
        scrollDown: 'Rolar para Baixo',
      },
      animation: {
        typing: 'Animação de digitação',
        fadeIn: 'Animação de aparição',
        slideUp: 'Animação de deslizar para cima',
      },
    },
    companiesSection: {
      title: 'Experiência Profissional',
      subtitle: 'Empresas com as quais trabalhei',
      displayMode: {
        timeline: 'Visualização em Linha do Tempo',
        grid: 'Visualização em Grade',
        list: 'Visualização em Lista',
      },
      company: {
        position: 'Cargo',
        period: 'Período',
        achievements: 'Principais Conquistas',
        technologies: 'Tecnologias Utilizadas',
        current: 'Atual',
        duration: 'Duração',
        location: 'Localização',
        type: 'Tipo de Emprego',
        fullTime: 'Tempo integral',
        partTime: 'Meio período',
        contract: 'Contrato',
        freelance: 'Freelancer',
        internship: 'Estágio',
      },
      sorting: {
        chronological: 'Cronológico',
        relevance: 'Por Relevância',
        company: 'Por Empresa',
        position: 'Por Cargo',
      },
      filters: {
        all: 'Todas as Empresas',
        byType: 'Por Tipo de Emprego',
        byTechnology: 'Por Tecnologia',
        byPeriod: 'Por Período',
      },
    },
    certificationsSection: {
      title: 'Certificações e Credenciais',
      subtitle: 'Certificações profissionais e conquistas',
      filters: {
        all: 'Todas as Categorias',
        category: 'Filtrar por Categoria',
        status: 'Filtrar por Status',
        issuer: 'Filtrar por Emissor',
        recent: 'Apenas Recentes',
      },
      certification: {
        issuer: 'Emitido por',
        date: 'Data',
        credentialId: 'ID da Credencial',
        verify: 'Verificar Credencial',
        expired: 'Expirado',
        valid: 'Válido',
        expiresOn: 'Expira em',
        noExpiration: 'Sem Expiração',
        renewed: 'Renovado',
        inProgress: 'Em Andamento',
      },
      categories: {
        cloud: 'Computação em Nuvem',
        development: 'Desenvolvimento de Software',
        security: 'Segurança',
        data: 'Dados e Analytics',
        project: 'Gerenciamento de Projetos',
        design: 'Design',
        other: 'Outros',
      },
      sorting: {
        date: 'Por Data',
        name: 'Por Nome',
        issuer: 'Por Emissor',
        category: 'Por Categoria',
        status: 'Por Status',
      },
      empty: {
        title: 'Nenhuma certificação encontrada',
        description: 'Nenhuma certificação corresponde aos filtros selecionados.',
        resetFilters: 'Redefinir Filtros',
      },
    },
    hardSkillsSection: {
      title: 'Habilidades Técnicas',
      subtitle: 'Tecnologias e ferramentas com as quais trabalho',
      allCategories: 'Todas as Categorias',
      proficiency: 'Proficiência',
      years: 'Anos',
      projects: 'Projetos',
      experience: 'Nível de Experiência',
      noSkills: 'Nenhuma habilidade encontrada para a categoria selecionada.',
      displayModes: {
        grid: 'Visualização em Grade',
        list: 'Visualização em Lista',
        chart: 'Visualização em Gráfico',
        compact: 'Visualização Compacta',
      },
      proficiencyLevels: {
        beginner: 'Iniciante',
        intermediate: 'Intermediário',
        advanced: 'Avançado',
        expert: 'Especialista',
        master: 'Mestre',
      },
      skills: {
        frontend: {
          title: 'Frontend',
          description: 'Desenvolvimento de interfaces de usuário com tecnologias modernas.',
        },
        backend: {
          title: 'Backend',
          description: 'Desenvolvimento de APIs e serviços web com tecnologias modernas.',
        },
        devops: {
          title: 'DevOps e Nuvem',
          description: 'Configuração e gerenciamento de serviços em nuvem e pipelines de deploy.',
        },
        database: {
          title: 'Banco de Dados',
          description: 'Design, otimização e gerenciamento de bancos de dados.',
        },
        mobile: {
          title: 'Mobile',
          description: 'Desenvolvimento de aplicações móveis para iOS e Android.',
        },
        tools: {
          title: 'Ferramentas e Utilitários',
          description: 'Ferramentas de desenvolvimento, IDEs e software de produtividade.',
        },
      },
      filters: {
        category: 'Filtrar por Categoria',
        proficiency: 'Filtrar por Proficiência',
        experience: 'Filtrar por Experiência',
        recent: 'Usadas Recentemente',
      },
    },
    projectsSection: {
      title: 'Projetos em Destaque',
      subtitle: 'Uma vitrine do meu trabalho recente',
      allCategories: 'Todas as Categorias',
      featuredOnly: 'Apenas Destacados',
      featured: 'Destaque',
      technologies: 'Tecnologias',
      challenges: 'Desafios',
      outcomes: 'Resultados',
      viewLive: 'Ver Ao Vivo',
      viewCode: 'Ver Código',
      viewDetails: 'Ver Detalhes',
      noProjects: 'Nenhum projeto encontrado para os filtros selecionados.',
      project: {
        role: 'Minha Função',
        duration: 'Duração',
        team: 'Tamanho da Equipe',
        status: 'Status',
        completed: 'Concluído',
        inProgress: 'Em Andamento',
        planned: 'Planejado',
        archived: 'Arquivado',
        client: 'Cliente',
        year: 'Ano',
        category: 'Categoria',
      },
      categories: {
        web: 'Desenvolvimento Web',
        mobile: 'Aplicativos Móveis',
        desktop: 'Aplicações Desktop',
        api: 'APIs e Backend',
        ecommerce: 'E-commerce',
        portfolio: 'Sites de Portfólio',
        dashboard: 'Dashboards',
        game: 'Jogos',
        tool: 'Ferramentas e Utilitários',
        other: 'Outros',
      },
      filters: {
        category: 'Filtrar por Categoria',
        technology: 'Filtrar por Tecnologia',
        status: 'Filtrar por Status',
        year: 'Filtrar por Ano',
        featured: 'Apenas Projetos em Destaque',
      },
      sorting: {
        recent: 'Mais Recentes',
        featured: 'Destacados Primeiro',
        name: 'Por Nome',
        category: 'Por Categoria',
        technology: 'Por Tecnologia',
      },
    },
    contactSection: {
      title: 'Contrate-me para seu próximo projeto incrível',
      subtitle: 'Vamos criar algo extraordinário juntos',
      description:
        'Vamos fazer algo novo, diferente e mais significativo ou tornar algo mais visual ou conceitual? Basta dizer oi!',
      socialInfos: {
        location: 'Belo Horizonte, MG, Brasil',
        timezone: 'UTC-3 (Horário de Brasília)',
        languages: 'Português, Inglês',
      },
      contactMethods: {
        title: 'Entre em Contato',
        email: 'Email',
        phone: 'Telefone',
        whatsapp: 'WhatsApp',
        telegram: 'Telegram',
        linkedin: 'LinkedIn',
        schedule: 'Agendar uma Chamada',
      },
      socialLinks: {
        title: 'Me Siga',
        github: 'GitHub',
        linkedin: 'LinkedIn',
        twitter: 'Twitter',
        instagram: 'Instagram',
        youtube: 'YouTube',
        medium: 'Medium',
        dev: 'Dev.to',
      },
      availability: {
        title: 'Status de Disponibilidade',
        available: 'Disponível para novos projetos',
        busy: 'Atualmente ocupado',
        unavailable: 'Não disponível',
        partTime: 'Disponível meio período',
        fullTime: 'Disponível tempo integral',
        freelance: 'Disponível para freelance',
        consulting: 'Disponível para consultoria',
      },
      form: {
        title: 'Envie-me uma mensagem',
        subtitle: 'Retornarei o mais breve possível',
      },
      fields: {
        name: 'Nome',
        email: 'Email',
        company: 'Empresa (Opcional)',
        budget: 'Budget (Opcional)',
        timeline: 'Cronograma do projeto (Opcional)',
        description: 'Descrição do projeto',
        message: 'Sua mensagem',
        send: 'Enviar Mensagem',
        sending: 'Enviando...',
        sent: 'Mensagem Enviada!',
        reset: 'Limpar Formulário',
      },
      budgetRanges: {
        small: 'Até R$ 25.000',
        medium: 'R$ 25.000 - R$ 75.000',
        large: 'R$ 75.000 - R$ 250.000',
        enterprise: 'R$ 250.000+',
        discuss: 'Vamos conversar',
      },
      validation: {
        nameRequired: 'Nome é obrigatório',
        nameMinLength: 'Nome deve ter pelo menos 2 caracteres',
        nameMaxLength: 'Nome deve ter menos de 50 caracteres',
        emailRequired: 'Email é obrigatório',
        emailInvalid: 'Por favor, insira um endereço de email válido',
        messageRequired: 'Mensagem é obrigatória',
        messageMinLength: 'Mensagem deve ter pelo menos 10 caracteres',
        messageMaxLength: 'Mensagem deve ter menos de 1000 caracteres',
        companyMaxLength: 'Nome da empresa deve ter menos de 100 caracteres',
      },
      messages: {
        success: 'Obrigado! Sua mensagem foi enviada com sucesso.',
        error: 'Desculpe, houve um erro ao enviar sua mensagem. Tente novamente.',
        networkError: 'Erro de rede. Verifique sua conexão e tente novamente.',
        serverError: 'Erro do servidor. Tente novamente mais tarde.',
        rateLimited: 'Muitas solicitações. Aguarde um momento antes de enviar outra mensagem.',
      },
      notifications: {
        successTitle: 'Mensagem Enviada!',
        successMessage: 'Obrigado por entrar em contato. Retornarei em breve.',
        errorTitle: 'Erro',
        errorMessage: 'Falha ao enviar mensagem. Tente novamente mais tarde.',
        copySuccess: 'Email copiado para a área de transferência!',
        copyError: 'Falha ao copiar endereço de email.',
      },
    },
  },
  footer: {
    contact: {
      title: 'Informações de Contato',
    },
    social: {
      title: 'Me Siga',
      visitProfile: 'Visite meu perfil no',
    },
    navigation: {
      title: 'Navegação Rápida',
    },
    availability: {
      title: 'Status de Disponibilidade',
      status: {
        available: 'Disponível para novos projetos',
        busy: 'Atualmente ocupado',
        unavailable: 'Não disponível',
      },
    },
    backToTop: 'Voltar ao Topo',
    copyright: '© {year} {name}. Todos os direitos reservados.',
    madeWith: 'Feito com ❤️ usando Vue.js',
    version: 'Versão {version}',
    lastUpdated: 'Última atualização: {date}',
    links: {
      privacy: 'Política de Privacidade',
      terms: 'Termos de Serviço',
      sitemap: 'Mapa do Site',
      rss: 'Feed RSS',
    },
  },
  errors: {
    pageNotFound: 'Página Não Encontrada',
    serverError: 'Erro do Servidor',
    networkError: 'Erro de Rede',
    loadingError: 'Erro de Carregamento',
    tryAgain: 'Tentar Novamente',
    goHome: 'Ir para Início',
    contactSupport: 'Contatar Suporte',
    errorCode: 'Código do Erro: {code}',
    errorMessage: 'Mensagem do Erro: {message}',
  },
  accessibility: {
    skipToContent: 'Pular para o conteúdo principal',
    skipToNavigation: 'Pular para a navegação',
    openInNewTab: 'Abre em nova aba',
    externalLink: 'Link externo',
    downloadFile: 'Baixar arquivo',
    toggleNavigation: 'Alternar menu de navegação',
    closeModal: 'Fechar modal',
    previousSlide: 'Slide anterior',
    nextSlide: 'Próximo slide',
    playVideo: 'Reproduzir vídeo',
    pauseVideo: 'Pausar vídeo',
    muteVideo: 'Silenciar vídeo',
    unmuteVideo: 'Ativar som do vídeo',
    fullscreen: 'Entrar em tela cheia',
    exitFullscreen: 'Sair da tela cheia',
    loading: 'Conteúdo está carregando',
    sortAscending: 'Ordenar crescente',
    sortDescending: 'Ordenar decrescente',
    filterResults: 'Filtrar resultados',
    clearFilters: 'Limpar todos os filtros',
    searchResults: '{count} resultados encontrados',
    noSearchResults: 'Nenhum resultado de pesquisa encontrado',
    pageOf: 'Página {current} de {total}',
    itemsPerPage: 'Itens por página',
  },
}
